spring:
  config:
    activate:
      on-profile: local

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:0/realms/fms

fms:
  security:
    oauth2:
      enabled: false
    api-key:
      enforced: false

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 0.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:0
          enabled: false

logging:
  level:
    com.fms: DEBUG
