spring:
  config:
    activate:
      on-profile: local

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:0/realms/fms

fms:
  security:
    oauth2:
      enabled: false
    api-key:
      enforced: false

logging:
  level:
    com.fms: DEBUG
